GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "lol",
    "important": false
}

###
GET http://localhost:3001/api/notes/6011db8cb28371287c9ae984

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "VS Code Rest Client testing logger",
    "important": false
}

###
PUT http://localhost:3001/api/notes/6013ebf39addc734ac767a7d HTTP/1.1
content-type: application/json

{
    "content": "lol",
    "important": false
}

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "root",
    "name": "admin",
    "password": "1234"
}

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "sakaricky91",
    "name": "Saka Ricky",
    "password": "jw76102907"
}

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNha2FyaWNreTkxIiwiaWQiOiI2MDFlYTg5YjlmN2Q2YTAwZWMzZTc3MTAiLCJpYXQiOjE2MTMxNDMxMTh9.8FUvbq8TXb_0vl5KEDyOqQ3Xj8VwakJ0RhiJRp-flgs

{
    "content": "VS Code Rest Client testing Token",
    "important": false
}

